Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -22,6 +22,7 @@ jobs:
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
+
     - name: Setup
       run: npm ci
 
@@ -29,7 +30,10 @@ jobs:
       run: |
         npm test -- --no-watch --no-progress --browsers=ChromeHeadless
         
-    - name: Coverage report
-      uses: romeovs/lcov-reporter-action@v0.2.16
+    - name: Unit Test Report ${{ matrix.node-version }}
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
       with:
-        lcov-file: ./coverage/mean-project/lcov.info
+        name: Unit test reports
+        path: /home/runner/work/MEAN-stack/MEAN-stack/junit_report/TEST-*.xml
+        reporter: java-junit
